// <auto-generated />
using System;
using BonsaiServer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BonsaiServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190221181551_SeedSession")]
    partial class SeedSession
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BonsaiServer.Database.Mutation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("End");

                    b.Property<int>("Plant1Id");

                    b.Property<int>("Plant2Id");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("Plant1Id");

                    b.HasIndex("Plant2Id");

                    b.HasIndex("UserId");

                    b.ToTable("Mutations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Plant1Id = 1,
                            Plant2Id = 2,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BonsaiServer.Database.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FlowersColorString")
                        .HasColumnName("FlowersColor")
                        .HasMaxLength(3);

                    b.Property<byte>("FlowersId");

                    b.Property<string>("LeavesColorString")
                        .HasColumnName("LeavesColor")
                        .HasMaxLength(3);

                    b.Property<byte>("LeavesId");

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.Property<string>("PotColorString")
                        .HasColumnName("PotColor")
                        .HasMaxLength(3);

                    b.Property<byte>("Rarity");

                    b.Property<byte>("Slot");

                    b.Property<string>("SoilColorString")
                        .HasColumnName("SoilColor")
                        .HasMaxLength(3);

                    b.Property<string>("StalkColorString")
                        .HasColumnName("StalkColor")
                        .HasMaxLength(3);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlowersColorString = "3db",
                            FlowersId = (byte)1,
                            LeavesColorString = "11f",
                            LeavesId = (byte)1,
                            Name = "SLLKYP",
                            PotColorString = "99b",
                            Rarity = (byte)2,
                            Slot = (byte)0,
                            SoilColorString = "175",
                            StalkColorString = "5b7",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            FlowersColorString = "df9",
                            FlowersId = (byte)1,
                            LeavesColorString = "5b1",
                            LeavesId = (byte)1,
                            Name = "NASEEPVRC",
                            PotColorString = "751",
                            Rarity = (byte)1,
                            Slot = (byte)0,
                            SoilColorString = "379",
                            StalkColorString = "157",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            FlowersColorString = "9fd",
                            FlowersId = (byte)1,
                            LeavesColorString = "d11",
                            LeavesId = (byte)1,
                            Name = "QGGNYKI",
                            PotColorString = "d91",
                            Rarity = (byte)3,
                            Slot = (byte)0,
                            SoilColorString = "555",
                            StalkColorString = "d3b",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            FlowersColorString = "d95",
                            FlowersId = (byte)1,
                            LeavesColorString = "d5d",
                            LeavesId = (byte)1,
                            Name = "IJZEYIOSSF",
                            PotColorString = "315",
                            Rarity = (byte)2,
                            Slot = (byte)0,
                            SoilColorString = "ff9",
                            StalkColorString = "df9",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            FlowersColorString = "b93",
                            FlowersId = (byte)1,
                            LeavesColorString = "1df",
                            LeavesId = (byte)1,
                            Name = "WUWYHB",
                            PotColorString = "b19",
                            Rarity = (byte)4,
                            Slot = (byte)0,
                            SoilColorString = "31f",
                            StalkColorString = "91d",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            FlowersColorString = "fb7",
                            FlowersId = (byte)1,
                            LeavesColorString = "915",
                            LeavesId = (byte)1,
                            Name = "VVPYYVE",
                            PotColorString = "957",
                            Rarity = (byte)3,
                            Slot = (byte)0,
                            SoilColorString = "f17",
                            StalkColorString = "3df",
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            FlowersColorString = "355",
                            FlowersId = (byte)1,
                            LeavesColorString = "dd5",
                            LeavesId = (byte)1,
                            Name = "PSITTA",
                            PotColorString = "5f1",
                            Rarity = (byte)2,
                            Slot = (byte)0,
                            SoilColorString = "1df",
                            StalkColorString = "f75",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            FlowersColorString = "97b",
                            FlowersId = (byte)1,
                            LeavesColorString = "9d5",
                            LeavesId = (byte)1,
                            Name = "RPFRI",
                            PotColorString = "d91",
                            Rarity = (byte)4,
                            Slot = (byte)0,
                            SoilColorString = "b79",
                            StalkColorString = "b77",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            FlowersColorString = "d95",
                            FlowersId = (byte)1,
                            LeavesColorString = "fb7",
                            LeavesId = (byte)1,
                            Name = "JPLXP",
                            PotColorString = "377",
                            Rarity = (byte)0,
                            Slot = (byte)0,
                            SoilColorString = "973",
                            StalkColorString = "1bb",
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            FlowersColorString = "733",
                            FlowersId = (byte)1,
                            LeavesColorString = "53b",
                            LeavesId = (byte)1,
                            Name = "GOUHZLOO",
                            PotColorString = "371",
                            Rarity = (byte)5,
                            Slot = (byte)0,
                            SoilColorString = "195",
                            StalkColorString = "593",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BonsaiServer.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(32);

                    b.Property<string>("Login")
                        .HasMaxLength(16);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(64);

                    b.Property<string>("Session")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "abc@wp.pl",
                            Login = "a",
                            PasswordHash = "28355a2d1a8636f26ebd23db7f7bc58f319f8b4d85282ddd308cfc5eeb18031b",
                            Session = "c8f0cbf67674c562415f802542e9e384ca056af3b8f2756acbfa7b0cfeeb6a95"
                        },
                        new
                        {
                            Id = 2,
                            Email = "radek@example.com",
                            Login = "radek",
                            PasswordHash = "450A10FAD8BC1453CF4690E7391F34DF4E7C3621CCC7E1B45699190C6ACC36E4",
                            Session = "450a10fad8bc1453cf4690e7391f34df4e7c3621ccc7e1b45699190c6acc36e4"
                        });
                });

            modelBuilder.Entity("BonsaiServer.Database.Mutation", b =>
                {
                    b.HasOne("BonsaiServer.Database.Plant", "Plant1")
                        .WithMany()
                        .HasForeignKey("Plant1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BonsaiServer.Database.Plant", "Plant2")
                        .WithMany()
                        .HasForeignKey("Plant2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BonsaiServer.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BonsaiServer.Database.Plant", b =>
                {
                    b.HasOne("BonsaiServer.Database.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
