// <auto-generated />
using System;
using BonsaiServer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BonsaiServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190222124350_SlotsFix")]
    partial class SlotsFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BonsaiServer.Database.Mutation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("End");

                    b.Property<int>("Plant1Id");

                    b.Property<int>("Plant2Id");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("Plant1Id");

                    b.HasIndex("Plant2Id");

                    b.HasIndex("UserId");

                    b.ToTable("Mutations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Plant1Id = 1,
                            Plant2Id = 2,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BonsaiServer.Database.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FlowersColorString")
                        .HasColumnName("FlowersColor")
                        .HasMaxLength(3);

                    b.Property<byte>("FlowersId");

                    b.Property<string>("LeavesColorString")
                        .HasColumnName("LeavesColor")
                        .HasMaxLength(3);

                    b.Property<byte>("LeavesId");

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.Property<string>("PotColorString")
                        .HasColumnName("PotColor")
                        .HasMaxLength(3);

                    b.Property<byte>("Rarity");

                    b.Property<byte>("Slot");

                    b.Property<string>("SoilColorString")
                        .HasColumnName("SoilColor")
                        .HasMaxLength(3);

                    b.Property<string>("StalkColorString")
                        .HasColumnName("StalkColor")
                        .HasMaxLength(3);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlowersColorString = "11f",
                            FlowersId = (byte)1,
                            LeavesColorString = "f91",
                            LeavesId = (byte)1,
                            Name = "BMXRE",
                            PotColorString = "155",
                            Rarity = (byte)5,
                            Slot = (byte)1,
                            SoilColorString = "3bb",
                            StalkColorString = "3f1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            FlowersColorString = "fbd",
                            FlowersId = (byte)1,
                            LeavesColorString = "555",
                            LeavesId = (byte)1,
                            Name = "JMZJLDH",
                            PotColorString = "5df",
                            Rarity = (byte)5,
                            Slot = (byte)2,
                            SoilColorString = "9b9",
                            StalkColorString = "d39",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            FlowersColorString = "9f1",
                            FlowersId = (byte)1,
                            LeavesColorString = "5b1",
                            LeavesId = (byte)1,
                            Name = "QFZKJQKX",
                            PotColorString = "f3d",
                            Rarity = (byte)4,
                            Slot = (byte)3,
                            SoilColorString = "fd3",
                            StalkColorString = "1f3",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            FlowersColorString = "3f3",
                            FlowersId = (byte)1,
                            LeavesColorString = "f73",
                            LeavesId = (byte)1,
                            Name = "SGBHGZAXB",
                            PotColorString = "119",
                            Rarity = (byte)0,
                            Slot = (byte)4,
                            SoilColorString = "bdb",
                            StalkColorString = "ddb",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            FlowersColorString = "919",
                            FlowersId = (byte)1,
                            LeavesColorString = "739",
                            LeavesId = (byte)1,
                            Name = "QSRUCQRUGXT",
                            PotColorString = "5f7",
                            Rarity = (byte)1,
                            Slot = (byte)5,
                            SoilColorString = "759",
                            StalkColorString = "71b",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            FlowersColorString = "3b1",
                            FlowersId = (byte)1,
                            LeavesColorString = "bfb",
                            LeavesId = (byte)1,
                            Name = "NFSLWQL",
                            PotColorString = "fbd",
                            Rarity = (byte)1,
                            Slot = (byte)1,
                            SoilColorString = "bb1",
                            StalkColorString = "511",
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            FlowersColorString = "5b3",
                            FlowersId = (byte)1,
                            LeavesColorString = "bd3",
                            LeavesId = (byte)1,
                            Name = "DQDUFLDACMZ",
                            PotColorString = "dd9",
                            Rarity = (byte)2,
                            Slot = (byte)2,
                            SoilColorString = "3f7",
                            StalkColorString = "bbf",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            FlowersColorString = "133",
                            FlowersId = (byte)1,
                            LeavesColorString = "597",
                            LeavesId = (byte)1,
                            Name = "JDQWYLWT",
                            PotColorString = "dbf",
                            Rarity = (byte)5,
                            Slot = (byte)3,
                            SoilColorString = "7fb",
                            StalkColorString = "5bf",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            FlowersColorString = "1fb",
                            FlowersId = (byte)1,
                            LeavesColorString = "5b9",
                            LeavesId = (byte)1,
                            Name = "WEAYKSVPV",
                            PotColorString = "137",
                            Rarity = (byte)3,
                            Slot = (byte)4,
                            SoilColorString = "1db",
                            StalkColorString = "591",
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            FlowersColorString = "f9d",
                            FlowersId = (byte)1,
                            LeavesColorString = "dbd",
                            LeavesId = (byte)1,
                            Name = "KLEVA",
                            PotColorString = "15b",
                            Rarity = (byte)5,
                            Slot = (byte)5,
                            SoilColorString = "71b",
                            StalkColorString = "75f",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BonsaiServer.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(32);

                    b.Property<string>("Login")
                        .HasMaxLength(16);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(64);

                    b.Property<string>("Session")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "abc@wp.pl",
                            Login = "a",
                            PasswordHash = "28355a2d1a8636f26ebd23db7f7bc58f319f8b4d85282ddd308cfc5eeb18031b",
                            Session = "c8f0cbf67674c562415f802542e9e384ca056af3b8f2756acbfa7b0cfeeb6a95"
                        },
                        new
                        {
                            Id = 2,
                            Email = "radek@example.com",
                            Login = "radek",
                            PasswordHash = "450a10fad8bc1453cf4690e7391f34df4e7c3621ccc7e1b45699190c6acc36e4",
                            Session = "450a10fad8bc1453cf4690e7391f34df4e7c3621ccc7e1b45699190c6acc36e4"
                        });
                });

            modelBuilder.Entity("BonsaiServer.Database.Mutation", b =>
                {
                    b.HasOne("BonsaiServer.Database.Plant", "Plant1")
                        .WithMany()
                        .HasForeignKey("Plant1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BonsaiServer.Database.Plant", "Plant2")
                        .WithMany()
                        .HasForeignKey("Plant2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BonsaiServer.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BonsaiServer.Database.Plant", b =>
                {
                    b.HasOne("BonsaiServer.Database.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
