// <auto-generated />
using System;
using BonsaiServer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BonsaiServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190221172143_SeedMutation")]
    partial class SeedMutation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BonsaiServer.Database.Mutation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("End");

                    b.Property<int>("Plant1Id");

                    b.Property<int>("Plant2Id");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("Plant1Id");

                    b.HasIndex("Plant2Id");

                    b.HasIndex("UserId");

                    b.ToTable("Mutations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Plant1Id = 1,
                            Plant2Id = 2,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BonsaiServer.Database.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FlowersColorString")
                        .HasColumnName("FlowersColor")
                        .HasMaxLength(3);

                    b.Property<byte>("FlowersId");

                    b.Property<string>("LeavesColorString")
                        .HasColumnName("LeavesColor")
                        .HasMaxLength(3);

                    b.Property<byte>("LeavesId");

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.Property<string>("PotColorString")
                        .HasColumnName("PotColor")
                        .HasMaxLength(3);

                    b.Property<byte>("Rarity");

                    b.Property<byte>("Slot");

                    b.Property<string>("SoilColorString")
                        .HasColumnName("SoilColor")
                        .HasMaxLength(3);

                    b.Property<string>("StalkColorString")
                        .HasColumnName("StalkColor")
                        .HasMaxLength(3);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlowersColorString = "7bb",
                            FlowersId = (byte)1,
                            LeavesColorString = "9b5",
                            LeavesId = (byte)1,
                            Name = "RHCHFFMUI",
                            PotColorString = "b3b",
                            Rarity = (byte)5,
                            Slot = (byte)0,
                            SoilColorString = "95f",
                            StalkColorString = "f9f",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            FlowersColorString = "577",
                            FlowersId = (byte)1,
                            LeavesColorString = "7f3",
                            LeavesId = (byte)1,
                            Name = "XEDCNM",
                            PotColorString = "bd9",
                            Rarity = (byte)0,
                            Slot = (byte)0,
                            SoilColorString = "f3b",
                            StalkColorString = "59f",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            FlowersColorString = "3d5",
                            FlowersId = (byte)1,
                            LeavesColorString = "b51",
                            LeavesId = (byte)1,
                            Name = "TQRKCCMD",
                            PotColorString = "bb9",
                            Rarity = (byte)5,
                            Slot = (byte)0,
                            SoilColorString = "93b",
                            StalkColorString = "dbf",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            FlowersColorString = "b15",
                            FlowersId = (byte)1,
                            LeavesColorString = "19b",
                            LeavesId = (byte)1,
                            Name = "QTREAM",
                            PotColorString = "53f",
                            Rarity = (byte)1,
                            Slot = (byte)0,
                            SoilColorString = "dd1",
                            StalkColorString = "f31",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            FlowersColorString = "3f1",
                            FlowersId = (byte)1,
                            LeavesColorString = "f19",
                            LeavesId = (byte)1,
                            Name = "HNFLNKXN",
                            PotColorString = "55d",
                            Rarity = (byte)4,
                            Slot = (byte)0,
                            SoilColorString = "9b5",
                            StalkColorString = "b57",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            FlowersColorString = "1f1",
                            FlowersId = (byte)1,
                            LeavesColorString = "bf1",
                            LeavesId = (byte)1,
                            Name = "GGOOIK",
                            PotColorString = "131",
                            Rarity = (byte)4,
                            Slot = (byte)0,
                            SoilColorString = "3df",
                            StalkColorString = "d9f",
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            FlowersColorString = "f91",
                            FlowersId = (byte)1,
                            LeavesColorString = "d75",
                            LeavesId = (byte)1,
                            Name = "IXXBJ",
                            PotColorString = "b9d",
                            Rarity = (byte)2,
                            Slot = (byte)0,
                            SoilColorString = "5dd",
                            StalkColorString = "1bf",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            FlowersColorString = "b73",
                            FlowersId = (byte)1,
                            LeavesColorString = "bb9",
                            LeavesId = (byte)1,
                            Name = "PEPDBP",
                            PotColorString = "5b1",
                            Rarity = (byte)1,
                            Slot = (byte)0,
                            SoilColorString = "bb7",
                            StalkColorString = "f31",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            FlowersColorString = "b57",
                            FlowersId = (byte)1,
                            LeavesColorString = "337",
                            LeavesId = (byte)1,
                            Name = "CDEKSWPHA",
                            PotColorString = "f75",
                            Rarity = (byte)4,
                            Slot = (byte)0,
                            SoilColorString = "3f5",
                            StalkColorString = "591",
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            FlowersColorString = "17f",
                            FlowersId = (byte)1,
                            LeavesColorString = "171",
                            LeavesId = (byte)1,
                            Name = "JSDFVWXPVFQ",
                            PotColorString = "1d3",
                            Rarity = (byte)2,
                            Slot = (byte)0,
                            SoilColorString = "f59",
                            StalkColorString = "3f3",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BonsaiServer.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(32);

                    b.Property<string>("Login")
                        .HasMaxLength(16);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(64);

                    b.Property<string>("Session")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "abc@wp.pl",
                            Login = "a",
                            PasswordHash = "28355A2D1A8636F26EBD23DB7F7BC58F319F8B4D85282DDD308CFC5EEB18031B",
                            Session = "IsThisWorking?"
                        },
                        new
                        {
                            Id = 2,
                            Email = "radek@example.com",
                            Login = "radek",
                            PasswordHash = "450A10FAD8BC1453CF4690E7391F34DF4E7C3621CCC7E1B45699190C6ACC36E4",
                            Session = "OtherSessionHash"
                        });
                });

            modelBuilder.Entity("BonsaiServer.Database.Mutation", b =>
                {
                    b.HasOne("BonsaiServer.Database.Plant", "Plant1")
                        .WithMany()
                        .HasForeignKey("Plant1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BonsaiServer.Database.Plant", "Plant2")
                        .WithMany()
                        .HasForeignKey("Plant2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BonsaiServer.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BonsaiServer.Database.Plant", b =>
                {
                    b.HasOne("BonsaiServer.Database.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
